<a href="https://colab.research.google.com/github/svdcvt/math_python_hse/blob/master/fall-2021/lectures/lecture12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Занятие 12: NumPy - Numerical Python

[[МИНИКОНТЕСТ]] (ссылка будет)

Открывайте семинар в Colab-е (кнопка выше, Open in Colab), после чего для изменения ноутбука необходимо нажать "Copy to Drive".

## NumPy

**NumPy** — библиотека языка Python, позволяющая (удобно) работать с многомерными массивами и матрицами. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении.

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)
 
Кстати, про NumPy недавно вышла [публикация](https://www.nature.com/articles/s41586-020-2649-2) в Nature.

In [1]:
!pip3 install numpy 
# так устанавливаются библиотеки если бы мы работали локально на собственных компьютерах
# но в Colab-e это не нужно, большинство библиотек тут уже предустановлено

In [2]:
import numpy as np 
# переименовываем то, как к нему кратко обращаться, 
# чтобы использовать его функции и методы (так можно сделать с любым модулем)

Основным типом данных NumPy является многомерный массив элементов одного типа — [numpy.ndarray](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html). Каждый подобный массив имеет несколько *измерений* или *осей* — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси. Многомерные массивы имеют 3 и более осей (например, тензоры).

In [3]:
vec = np.array([1, 2, 3])
vec.ndim # количество осей

1

In [4]:
# можно указать желаемый тип
vec_str = np.array([10, 100, 10000, 1], dtype=str)
print(vec_str)
vec_str[0] = 1000000 
# заметьте как мы обновляем элемент числом, но в массиве он становится строкой, так как у массива мы указали тип элементов
print(vec_str)

['10' '100' '10000' '1']
['10000' '100' '10000' '1']


In [5]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом shape:

In [6]:
vec.shape

(3,)

Чтобы узнать тип элементов и их размер в байтах:

In [7]:
mat.dtype.name

'int64'

In [8]:
mat.itemsize

8

In [9]:
# многомерные массивы
tens = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]]) 
print(tens, tens.ndim, tens.shape, sep='\n')

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3
(2, 2, 2)


#### Создание массивов

Есть несколько способов сформировать массив в NumPy:

* Передать итерируемый объект в качестве параметра функции array (можно также явно указать тип элементов):

In [10]:
A = np.array([1, 2, 3])
A, A.dtype

(array([1, 2, 3]), dtype('int64'))

In [11]:
A = np.array([1, 2, 3], dtype=float)
A, A.dtype

(array([1., 2., 3.]), dtype('float64'))

* Воспользоваться функциями zeros, ones, empty, identity, full если вам нужен объект специального вида:

In [12]:
np.zeros((3,))

array([0., 0., 0.])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.empty((2,3)) 
# заполняется "какими-то" числами, предполагается использовать 
# такой массив, чтобы потом туда вставлять необходимые значения

array([[4.68322634e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.full((2,3,4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

* Воспользоваться функциями arange (в качестве параметров принимает левую и правую границы последовательности и **шаг**) и linspace (принимает левую и правую границы и **количество элементов**) для формирования последовательностей:

In [17]:
np.arange(2, 20, 3) # аналогично стандартной функции range python, правая граница не включается

array([ 2,  5,  8, 11, 14, 17])

In [18]:
np.arange(2.5, 8.7, 0.9) # но может работать и с вещественными числами

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [19]:
np.linspace(2, 18, 14) # правая граница включается (по умолчанию)

array([ 2.        ,  3.23076923,  4.46153846,  5.69230769,  6.92307692,
        8.15384615,  9.38461538, 10.61538462, 11.84615385, 13.07692308,
       14.30769231, 15.53846154, 16.76923077, 18.        ])

* Изменить размеры существующего массива с помощью reshape (при этом количество элементов должно оставаться неизменным):

In [20]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Вместо значения длины массива по одному из измерений можно указать -1 — в этом случае значение будет рассчитано автоматически:

In [21]:
np.arange(8).reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

* Транспонировать существующий массив:

In [22]:
C = np.arange(6).reshape(2, -1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

* Повторить существующий массив:

In [24]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [25]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

- Превратить многомерный массив в вектор:

In [26]:
tens = np.arange(8).reshape(2,2,2)
line = tens.flatten()
tens.shape, line, line.shape

((2, 2, 2), array([0, 1, 2, 3, 4, 5, 6, 7]), (8,))

* С помощью функции ```np.logspace``` создать массив из равноудаленных элементов в логарифмической шкале

In [27]:
np.logspace(2, 5, num=10, base=2, dtype=int) # 10 ~равноудаленных целых чисел от 2^2 до 5^2

array([ 4,  5,  6,  8, 10, 12, 16, 20, 25, 32])

* С помощью функции ``np.linspace`` создать массив из равноудаленных элементов в линейной шкале

In [28]:
np.linspace(10, 100, 3)

array([ 10.,  55., 100.])

#### Random
[Сабмодуль ```np.random```](https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html) позволяет создавать массивы с элементами из вероятностных распределений. Создадим следующие массивы:
1. Массив из 10 случайных чисел из $U([0,1))$ (равномерное распределение на полуотрезке [0, 1))
2. Массив 3х5 случайных чисел из $\mathcal{N}(0,1)$ (стандартное нормальное распределение)
3. Массив из случайных целых чисел от 0 до 10 размером 15
4. Массив из случайной подвыборки чисел от 0 до 20 размером 15 (то же что 3, но без повторений)


In [29]:
np.random.random((10,))

array([0.91344625, 0.78553141, 0.31816434, 0.24766274, 0.24974419,
       0.11683865, 0.64282884, 0.15480234, 0.95510027, 0.69998443])

In [30]:
np.random.randn(3, 5)

array([[ 1.94021118,  0.72173454,  0.33248904,  1.83883023, -0.29660131],
       [-1.27443508,  1.45896927,  0.15923024, -1.10374704, -0.15707214],
       [-0.70376166, -0.13594343, -1.83101006,  0.71909441, -2.08166674]])

In [31]:
np.random.randint(0, 10, size=(15,))

array([6, 8, 2, 2, 4, 2, 2, 2, 8, 4, 7, 2, 4, 9, 3])

In [32]:
np.random.choice(np.arange(0, 20), size=(15,), replace=False)

array([15, 10,  3,  4,  8, 19, 13,  7,  1,  6, 11, 17, 14, 12,  5])

### Обработка массивов

С помощью `np.where` для случайного вектора вернем вектор, где отрицательные элементы заменены 0

In [33]:
a = np.random.randn(5) * 4 - 1
a, np.where(a > 0, a, 0) 
# также третьим аргументом можно подать массив того же размера, 
# тогда заменятся элементы не соответсвующие условию будут заменяться соответствующими занчениями

(array([-2.17605305, -5.56577037,  2.23942859,  2.35054919, -1.75475266]),
 array([0.        , 0.        , 2.23942859, 2.35054919, 0.        ]))

С помощью `np.clip` можно ограничить значения массива (снижу и/или сверху):

In [34]:
np.clip(a, 0, 1)

array([0., 0., 1., 1., 0.])

С помощью `np.vstack` и `np.hstack` можно "стакать" (stack - укладывать/накладывать друг на друга) массивы по вертикали и по горизонтали:

In [35]:
a, b = np.full((2, 3), 1), np.full((3, 2), 2)
# тут важно чтобы одна из осей по которой мы стакаем у обоих массивов была одинаковая
print(np.vstack([a, b.T]), '\n')
print(np.hstack([a.T, b]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]] 

[[1 1 2 2]
 [1 1 2 2]
 [1 1 2 2]]


С помощью `np.unique` можно составить массив, в котором первый столбец - уникальные значения вектора, а второй столбец соответсвует тому сколько раз соответственный элемент первого столбца встретился в векторе

In [36]:
a = np.random.randint(-2, 2, 20)
print(a, '\n')
elements, frequency = np.unique(a, return_counts=True)
print(elements, '\n')
print(frequency)

[-2  0 -1 -2 -1 -1 -2  1  0  1 -2 -2 -1 -1 -1  0  0 -1  0 -2] 

[-2 -1  0  1] 

[6 7 5 2]


#### Базовые операции

* Базовые арифметические операции над массивами выполняются поэлементно:

In [37]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [38]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [40]:
A * 1.0 / B

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [41]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [43]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

Отдельно обратим внимание на то, что умножение массивов также является **поэлементным**, а не матричным:

In [44]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

Для выполнения матричного умножения необходимо использовать функцию dot:

In [45]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

Для умножения векторов или матриц можно также использовать оператор `@`:

In [46]:
A @ B

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [47]:
np.array([1, 2, 3, 4]) @ np.array([1, 1, 1, 1])

10

Поскольку операции выполняются поэлементно, операнды бинарных операций должны иметь одинаковый размер. Тем не менее, операция может быть корректно выполнена, если размеры операндов таковы, что они могут быть расширены до одинаковых размеров. Данная возможность называется [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting):
![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [48]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

* Некоторые операции над массивами (например, вычисления минимума, максимума, суммы элементов) выполняются над всеми элементами вне зависимости от формы массива, однако при указании оси выполняются вдоль нее (например, для нахождения максимума каждой строки или каждого столбца):

In [49]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
A.min()

0

In [51]:
A.max(axis=1)

array([2, 5, 8])

In [52]:
A.sum(axis=1)

array([ 3, 12, 21])

Понять и научиться классно использовать эту главную особенность библиотекм - искусство! И только с опытом (сыном ошибок трудных) можно овладеть данным навыком. Надеемся вы попробуете немного его получить в домашнем задании.

#### Индексация

Для доступа к элементам может использоваться [много различных способов](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), рассмотрим основные.

* Для индексации могут использоваться конкретные значения индексов и срезы (slice), как и в стандартных типах Python. Для многомерных массивов индексы для различных осей разделяются запятой. Если для многомерного массива указаны индексы не для всех измерений, недостающие заполняются полным срезом (:).

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[2:5]

array([2, 3, 4])

In [55]:
a[3:8:2]

array([3, 5, 7])

In [56]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [57]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [58]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [59]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [60]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

* Также может использоваться индексация при помощи списков индексов (по каждой из осей):

In [61]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [62]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

* Может применяться логическая индексация (при помощи логических массивов):

In [63]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [65]:
A[np.logical_and(A != 7, A % 5 != 3)] # также можно использовать логические операции

array([ 0,  1,  2,  4,  5,  6,  9, 10])

#### Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы. Попробуем посчитать скалярное произведение 2 больших векторов:

In [66]:
SIZE = 10000000

A_quick_arr = np.random.normal(size = (SIZE,))
B_quick_arr = np.random.normal(size = (SIZE,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [67]:
%%time
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]

CPU times: user 4.58 s, sys: 24.4 ms, total: 4.6 s
Wall time: 4.63 s


In [68]:
%%time
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(SIZE)])

CPU times: user 3.35 s, sys: 364 ms, total: 3.72 s
Wall time: 3.72 s


In [69]:
%%time
ans = np.sum(A_quick_arr * B_quick_arr)

CPU times: user 34.7 ms, sys: 862 µs, total: 35.6 ms
Wall time: 42.9 ms


In [70]:
%%time
ans = A_quick_arr.dot(B_quick_arr)

CPU times: user 21.3 ms, sys: 6.59 ms, total: 27.9 ms
Wall time: 18.9 ms


NumPy работает быстро по нескольким причинам:
* Массивы хранятся в непрерывном участке памяти, а все элементы имеют один и тот же тип
* Для вычислений по возможности используются библиотеки линейной алгебры вроде BLAS

Посмотреть, какая библиотека используется у вас, можно в конфигурации NumPy:

In [71]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


### Примеры векторизации вычислений на NumPy


Разберём несколько задач (из [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)), где NumPy может существенно ускорить вычисления и упростить код.

Дан четырёхмерный массив. Как получить двумерный массив, в котором элемент с индексами $(i, j)$ содержит сумму всех элементов исходного массива, у которых первые два индекса — это $(i, j)$?

In [72]:
A = np.random.randint(0,1000,(2,5,20,25))
res = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(res)

[[264963 244491 246183 253922 242484]
 [248381 243861 241902 251258 241533]]


Даны одномерные массивы A и B. Элементы массива B принимают значения от 0 до `len(A) - 1`. Требуется прибавить единицу ко всем элементам A, чьи индексы записаны в B. Если индекс встречается в B несколько раз, то надо прибавить единицу для каждого такого вхождения.

In [73]:
A = np.ones(10)
B = np.random.randint(0,len(A),20)
print(A)
print(B)
A += np.bincount(B, minlength=len(A))
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 4 9 9 9 5 8 3 5 0 0 1 7 6 7 5 7 6 4 5]
[3. 2. 1. 3. 3. 5. 3. 4. 2. 4.]


Даны одномерный массив A и число n. Вычислите массив B, в котором i-й элемент равен среднему значению элементов с i-го по (i+n-1)-й в массиве A.

In [74]:
def moving_average(Z, n=3) :
    ret = np.cumsum(Z, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
A = np.random.randint(0, 10, 20)
print(A)
print(moving_average(A, n=3))

[4 2 5 4 2 4 7 6 4 9 1 2 1 9 8 3 8 2 3 4]
[3.66666667 3.66666667 3.66666667 3.33333333 4.33333333 5.66666667
 5.66666667 6.33333333 4.66666667 4.         1.33333333 4.
 6.         6.66666667 6.33333333 4.33333333 4.33333333 3.        ]
