**Дедлайн: 25.12.2020**

## Numpy (7 баллов)

NumPy - модуль Python предназначенный для эффективных матричных вычислений. Модуль реализован на языке C и предоставляет огромное количество встроенных операций над матрицами, поэтому использование циклов `while` и `for` считается дурным тоном. Про преимущества NumPy над обычными списками Python можно почитать [в этом посте](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists).
В реальной работе с Python очень часто приходится разбираться со сторонними модулями, поэтому, важно научиться пользоваться официальной документацией. NumPy имеет отличную [документацию](https://numpy.org/doc/1.19/), в которой подробно описаны функции, аргументы, а также приведены примеры использования. Более того, документация содержит [руководство по использованию для начинающих](https://numpy.org/doc/1.19/user/absolute_beginners.html), поэтому, для начала ознакомьтесь с ним.

Установить модуль можно через `pip` или `conda`. Если у вас есть сложности с установкой сторонних модулей (например, намучались с установкой Pygame), то лучше делайте это задание в Google Colab.  

Импортируем модуль:

In [ ]:
import numpy as np

### Задание 1

• Документация содержит [руководство по использованию для начинающих](https://numpy.org/doc/1.19/user/absolute_beginners.html). Чтобы разобраться в том, как работать с модулем и выполнить последующие задания прочитайте это руководство.

**[0.2 Балла]** С помощью функции ```np.arange``` и метода изменения формы массива создайте массив четных чисел от 0 до 100 (не включительно) такой, что в каждой строке новый десяток, то есть:
```
0, 2...
10, 12...
...
90, 92...
```

In [ ]:
# code

**[0.2 Балла]** Создайте массив степеней 2 (целыми числами) от 0 до 10 с помощью функции ```np.logspace```

In [ ]:
# code

**[0.2 Балла]** Создайте массив равноудаленных 50 точек на отрезке [0,1] (первая точка 0, последняя 1) с помощью функции ``np.linspace``

In [ ]:
# code

**[0.2 Балла]** Напишите код, который воспроизводит выход ячейки ниже (будте аккуратны и не перезапускайте просто так ячейку ниже, иначе потеряете ее выход)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**[0.4 Балла] Random**  
Изучите функции [сабмодуля ```np.random```](https://docs.scipy.org/doc/numpy-1.14.1/reference/routines.random.html) и создайте следующие массивы:
1. Массив из 10 случайных чисел из $U([0,1])$ (равномерное распределение на отрезке [0, 1])
2. Массив 10х100 случайных чисел из $\mathcal{N}(0,1)$ (стандартное нормальное распределение)
3. Массив из случайных целых чисел от 0 до 100 размером 42 (с повторениями)
4. Массив из случайной подвыборки чисел от 0 до 100 размером 42 (то же что 3, но без повторений)

**[0.2 Балла]** С помощью `np.where` для случайного вектора верните вектор, где отрицательные элементы заменены 0

**[0.2 Балла]** Дан массив 10х3, который будет использован как массив с цветами RGB (каждый канал обозначается целым числом от 0 до 255). С помощью `np.clip` ограничьте значения массива.

**[0.2 Балла]** С помощью `np.vstack` и `np.hstack` склейте две квадратные матрицы `a` и `b` размера 3 по вертикали и по горизонтали

In [ ]:
a = np.arange(9).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

**[0.2 Балла]** Для данного вектора с помощью `np.unique` составьте массив, в котором первый столбец - уникальные значения вектора, а второй столбец соответсвует тому сколько раз соответственный элемент первого столбца встретился в векторе (строки упорядочены по убыванию частоты элемента в векторе)

**[0.2 Балла]** С помощью `np.insert` в случайный вектор вставьте на четные индексы нули.

#### Индексирование

In [ ]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**[0.3 Балла]** Напишите код, который воспроизводит выход ячеек ниже (будте аккуратны и не перезапускайте просто так ячейки ниже, иначе потеряете выход).

In [ ]:
matrix[...]  # напишите правильный код вместо троеточия

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
matrix[...]  # напишите правильный код вместо троеточия

array([[ 2],
       [ 7],
       [12]])

In [ ]:
matrix[...]  # напишите правильный код вместо троеточия

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**[0.2 Балла]** Создайте вектор из случайных семи элементов матрицы `matrix`

**[0.2 Балла]** Создайте случайный масиив 4х4 и верните индексы положительных элементов (`np.argwhere`)

#### Математические операции

**[0.2 Балла]** Сравните время работы встроенной функции `sum` и `np.sum` на матрице `a` (с помощью `%timeit`)

In [ ]:
a = np.random.randint(10, size=(100, 100))

**[0.2 Балла]** Создайте любые два вектора и перемножьте их, чтобы получить матрицу (в NumPy вектор это строка, а не столбец, поэтому $A = x^Ty$)

**[0.2 Балла]** У предыдущей матрицы возьмите ее диагональные элементы и создайте матрицу с такой же диагональю, но остальные элементы нулевые (`np.diag`) 

**[0.5 Балла]** Создайте симметричную матрицу случайных целых чисел от в интервале от 1 до 10 размера 5х5 и посчитайте следующее ([сабмодуль `np.linalg`](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)):
- определитель матрицы
- обратную матрицу
- произведение матрицы на саму себя
- собственные вектора

**[0.3 Балла]** Для данных двух векторов посчитайте их косинусное расстояние:
$$cos(a,b) = \frac{(a,b)}{|a||b|},$$
где $|a| = \sqrt{(a,a)}$,  $(a,b) = ab^T$

In [ ]:
a = np.ones(10)
b = np.full(10, 2)

**[0.2 Балла]** Для матрицы A посчитайте ее норму Фробениуса:
$$\|A\|_F = \sqrt{tr(AA^*)}$$

In [ ]:
A = np.random.randint(-2, 2, (4, 4)) + 1j * np.random.random((4, 4))

**[0.5 Балла]** Создайте случайный (любой) массив 100х100
- Найдите его среднее - общее, по столбцам и по строкам (`np.mean`)
- Посчитайте стандартное отклонение по строкам
- Дисперсию по столбцам
- Медиану
- Минимальное значение по строкам
- Максимальное значение по столбцам
- 9-персентиль.

**[0.5 Балла]** Напишите функцию, которая находит сумму квадратов положительных элементов одномерного массива.

In [ ]:
def get_squares(a: np.ndarray) -> float:
    ### YOUR CODE
    pass

assert get_squares(np.array([1,-2,3])) == 10

**[0.5 Балла]** Коля -- мастер покера и умеет выигрывать только целые суммы денег от 0 до n - 1. Коля решил сыграть на турнире. На вход подаётся массив `p` размера $n$, где `p[i]` -- вероятность, что Коля выиграет на турнире $i$ рублей ($\sum_{i=1}^{n}p_i =1$, $p_i \geqslant 0, \forall i$). Посчитайте математическое ожидание выигрыша Коли на турнире.

In [ ]:
def expected_reward(p: np.ndarray) -> float:
    ### YOUR CODE
    pass

assert expected_reward(np.array([0.4, 0.5, 0.1])) == 0.7

**[0.5 Балла]** Дана квадратная матрица `A`. Посчитайте произведение диагональных элементов матрицы, __строго__ превосходящих среднее значение элементов всей матрицы.

__Подсказка__: взять диагональ матрицы - `np.diag()`, произведение элементов массива - `np.prod()`, среднее значение в массиве - `np.mean()`.

In [ ]:
def prod_upper_avg_diagonal(a: np.ndarray) -> float:
    # YOUR CODE

assert prod_upper_avg_diagonal(np.array([[ 0,  1,  2,  3],
                                         [ 4,  5,  6,  7],
                                         [ 8,  9, 10, 11],
                                         [12, 13, 14, 15]])) == 150

**[0.5 Балла]** Дано число $n$. Создайте матрицу $A$ размера $n \times n$ такую, что $A[i][j] = i \cdot j$. Нумерация строк и столбцов начинается с нуля.

In [ ]:
def create_ij(n: int) -> np.ndarray:
    ### YOUR CODE

assert np.all(create_ij(5) == np.array([[ 0,  0,  0,  0,  0],
                                        [ 0,  1,  2,  3,  4],
                                        [ 0,  2,  4,  6,  8],
                                        [ 0,  3,  6,  9, 12],
                                        [ 0,  4,  8, 12, 16]]))

## Pandas (6 баллов)
Модуль `pandas` предназначен для работы с табличными большими данными. Иногда его функционал похож на какой-нибудь Microsoft Excel, за исключением того, что это все внутри python-а и порой использовать программисту намного удобнее и привычнее. Как и `numpy`, является одной из основных библиотек из machine-learning набора.
<img src="https://24.kz/media/k2/items/cache/8ddf184842db861ab0b18c352a42b866_XL.jpg" alt="ПАНДЫ!!!" width="500"/>

In [ ]:
import pandas as pd

`pandas` также имеет достаточно хорошую [документацию](https://pandas.pydata.org/pandas-docs/stable/index.html) с руководставами по использованию. Первым делом ознакомьтесь с руководством [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html#min).

In [ ]:
# непонятный код, чтобы скачать архив с таблицой данных про велосипеды, просто запустите ячейку!
!wget -O data.zip https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip 
!unzip data.zip

--2020-12-16 00:55:36--  https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 279992 (273K) [application/x-httpd-php]
Saving to: ‘data.zip’

data.zip            100%[===================>] 273.43K   190KB/s    in 1.4s    

2020-12-16 00:55:39 (190 KB/s) - ‘data.zip’ saved [279992/279992]

Archive:  data.zip
  inflating: Readme.txt              
  inflating: day.csv                 
  inflating: hour.csv                


### Основы (1 балл)

• С помощью функции `read_csv` [(ссылка на документацию)](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) загрузите файл `hour.csv` в переменную с именем `data`. Укажите в параметрах, что первая строка - строка с названиями столбцов (`header`), а первый столбец - индекс (`index_col`). 

In [ ]:
data = # YOUR CODE

• С помощью `tail()` выведите последние 10 строк.

• С помощью `shape` (прямо как в numpy!) определите число строк и столбцов

• С помощью `index` и `columns` выведите индекс и названия столбцов датасета

• С помощью `describe` получите основные статистики для каждой колонки

• С помощью `info()` получите информацию о датасете и опишите, что вы с ее помощью можете понять о данных. С помощью [текстового описания данных](https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset#) кратко опишите датасет.

### Создание таблиц (1 балла)

In [ ]:
# создание из списка списков, присваивая имена столбцам
states = pd.DataFrame(
            data = [['NJ', 'Towaco', 'Square'], 
                     ['CA', 'San Francisco', 'Oval'], 
                     ['TX', 'Austin', 'Triangle'], 
                     ['MD', 'Baltimore', 'Square'],
                     ['OH', 'Columbus', 'Hexagon'], 
                     ['IL', 'Chicago', 'Circle']],
            columns = ['State', 'City', 'Shape'])
states

•
Создайте датафрейм из случайного (или нет - это на ваше усмотрение) нампай-массива, присвоив столбцам какие-нибудь названия названия. Сделайте одну из колонок индексом (`set_index`, будьте внимательны с параметром `inplace`).

•
Создайте датафрейм из словаря, где столбцы это название фруктов, а индекс это имена, значения датафрейма - число купленных отдельных фруктов каждым человеком. 

•
Сохраните любой из выше созданных массивов в формате `csv` без названия столбцов (используйте параметры функции `to_csv`)

### Изменение (1 балл)

Очевидно, наши табличные данные можно (и нужно!) менять. Как и обычные контейнеры (список, нампай эррэй, значения словаря), датафрейму можно присвоить новые значение. Делается это так:

In [ ]:
states.iloc[0, -1] = 'Flower'
states

Мы можем добавлять новый столбец:

In [ ]:
states['Size'] = [2**i for i in range(states.shape[0])] 
states

Или новую строку

In [ ]:
states.loc[10] = ['KL', 'Moscow', 'Box', 42]
states

•
Вернем к нашим велосипедам. Скопируйте датасет в новую переменную `data_upd`. Предположим в наших данных ошибка, и по воскресеньям на самом деле никаких покупок не совершалось. Соответствующие "покупкам" столбцы занулите в тех строках, которые соответствуют воскресенью (0 weekday).

In [ ]:
data_upd = 

•
С помощью `insert` добавьте столбец сразу после `windspeed`, который является произведением `temp` на `hum`, назовите его `feel`.

• Покажите первые 15 строк обновленного датафрейма.


### Пропуски в данных (1 балл)
В нашем датасете изначально не было NaN (not a number, None) значений, которые часто возникают, если, например, какое-то значение забыли записать в таблицу, либо просто таких данных не существовало, но для полноты таблицы какое-то значение надо было поставить и поставили NaN (например таблица, у которой индекс это год, а столбцы это демографические показатели, и столбец "пользователи интернета" до середины прошлого века ничем не заполнишь).

Искусственным способом добавим "наны" в таблицу:

In [ ]:
data_nan = data.copy()
for _ in range(np.random.randint(0, 5000)):
    data_nan.iloc[np.random.randint(0, data.shape[0]), np.random.randint(0, data.shape[1])] = np.nan


•
С помощью `isnull` и `sum` посмотрите сколько всего пропущенных значений, сколько в каждом столбце?

•
С помощью `fillna` заполните NaN средним или модой. 


• Проверьте, есть ли у нас теперь пропущенные значения?

• Возможно, что так просто заполнять пропущенные значения может быть неосмысленно или даже ошибочно. Почему? Подумайте, как было бы правильнее заполнить пропущенные значения в случае нашего датасета? (отталкивайтесь от данных!) Необязательно писать решение в виде кода, будет достаточно словами.

### Фильтрация данных (2 балла)

Считайте данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?